manifest = "e38ec6c9333c10821835d9ce3dd2e35053e3f32702ab3abbea80dbfacbaf9fd8"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.56.0" ]
revision = "9d1a6e0a4a74ad3af0ade7285ab5edd52c6fd860"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.56.0" ]
revision = "edb8562f816250216903f89ec4d9ac0961a922a1"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.56.0" ]
revision = "baeb2fb09197e1422a40481e9080e17c75cd50cf"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.56.0" ]
revision = "37f8e9a9f7a9e93ab1ebed5fc2f8614d3c52e710"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.56.0" ]
revision = "9641085a42a25ca196d08d542862616f877cf693"
