manifest = "13224747def90321e742ef88d5cdb26738fd23156db06fb7a73cf26e7bdbbdb1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.59.0" ]
revision = "b8a861102681be539be9c889cd643986f171c364"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.59.0" ]
revision = "ec90e8c6b2f388644b586d11eb1a3543028fa1f5"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.59.0" ]
revision = "6019dca782a1a7b7e7e105d67216d8f824423101"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.59.0" ]
revision = "06f80557aba297b003135535cdc69de522326c50"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.59.0" ]
revision = "103e6b45eec26ac91156cfeb45450fa8ec375369"
