manifest = "6d2f7724865acf56cf5e284de6256aa8454549f087cb0f71b1f68ed58d443dbb"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.65.0" ]
revision = "d464187703a522223f9f3b01b4fbe8f8ae05fad6"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.65.0" ]
revision = "7268ab966b715d5702f1a2b98990626f1c193e6f"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.65.0" ]
revision = "2c6eae3c5a1b1278f35ea09e2df05f59c9303b12"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.65.0" ]
revision = "287f9aba51b4f6f6209d528d12918f048d940512"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.65.0" ]
revision = "32153d21d6a4f5a334d859adb7acb2d005a190ff"
