manifest = "7508725e45336b5480a31d2a62ced1a5fa9b27e49bcb4b5f6894d56af5505550"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.63.0" ]
revision = "9b56785b10414925c36e556e091726b7bd8611c3"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.63.0" ]
revision = "f4f11472a3df6451547ae5c1023434485590e80e"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.63.0" ]
revision = "8be308e3f8c821d50b67c579c52fe35f3c3310e9"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.63.0" ]
revision = "a65be8666c3771ce7660385cdfaf8dbf19dffcc4"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.63.0" ]
revision = "ffb2665a30e3ea4d941cbe5a4ee89e2e1dacd941"
