manifest = "f32cc8458431d5258c5aa32241a807d3938e2835c9b6242dc8e3ac32a870b755"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.57.0" ]
revision = "e4476f3159e98aebaa3a057bd2670653cb778d48"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.57.0" ]
revision = "ee7d5652f970bde066501c7cee1d0d2ad43c2348"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.57.0" ]
revision = "08aef274380d048f40aea0f40be03d3c943c0917"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.57.0" ]
revision = "1c6733c3798004871da07f1ca08b533b1293b597"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.57.0" ]
revision = "b71c8285ba07563884f165ae769db3cd5a5dc45a"
