targets = [ "//:move" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.57.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
version = "1.57.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.57.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.57.0"
